sudo: enabled
language: python
python:
    - "3.4"
    - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libeigen3-dev libfftw3-dev

install:
    - pip install --upgrade -r requirements.txt
    - python setup.py develop

script:
    - py.test --doctest-modules --disable-warnings spexy

