language: python
python:
    - "3.4"
    - "3.6"
    
addons:
  apt:
    packages: &common_packages
      - gcc-6
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

install:
    - export CC=gcc-6
    - export CXX=g++-6
    - pip install -r requirements.txt
    - python setup.py develop

script:
    - py.test --doctest-modules spexy

